### ISSUE TITLE
[BUG] Newsletter Not Working

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-docs#131]
The Newsletter form on the footer is not working at the moment, when users input their email address, then click `Subscribe`, an error display `Something went wrong: Internal Server Error`.

## Expected Behavior

The newsletter should work and when users click on `Subscribe`, we need to add them to the Ghost member.

### Current Behavior

![CleanShot 2023-09-22 at 00 05 39@2x](https://github.com/webb-tools/webb-docs/assets/60747384/0ad3ead9-e4d0-48f9-a1ab-2361a33a9197)

Maybe reference this comment https://github.com/webb-tools/webb-dapp/issues/1342#issuecomment-1683721385.

**Comment by monaiuu** [comment]
This is the custom HTML code for Ghost subscription used on webflow, this should work for on doc site as well: 

> <div style="min-height: 58px;max-width: 440px;margin: 0 auto;width: 100%"><script src="https://cdn.jsdelivr.net/ghost/signup-form@~0.1/umd/signup-form.min.js" data-button-color="#000000" data-button-text-color="#FFFFFF" data-site="https://blog.webb.tools/" async></script></div>
